version: '3.7'

services:
    flask:
        build: .
        command: python -u run.py
        ports:
            - '5000:5000'
        volumes:
            - .:/app
        links:
            - db
    db:
        image: mongo:latest
