version: '3'

services:
    flask:
        build: .
        # command: python -u server/run.py
        ports:
            - '5000:5000'
        volumes:
            - ./:/app
        links:
            - db
        env_file: .env
        depends_on:
            - db
    db:
        image: mongo:latest
